USE Stat; 
GO 

--TRUNCATE TABLE dbo.RawAvia;

--SELECT CONFIGA-SEATED as different FROM dbo.RawAvia ORDER BY 1 ASC;

--SELECT CAST(CONFIGA AS int)*1000 FROM RawAvia ORDER BY CONFIGA DESC;

--SELECT PARSE(SEATED AS int)*1000 FROM RawAvia ORDER BY SEATED DESC;
/*
DECLARE @column AS varchar(50) = 'FLTID';
SELECT @column FROM RawAvia GROUP BY @column ORDER BY @column;
*/
/*
SELECT SEATED FROM RawAvia GROUP BY SEATED ORDER BY 1;
*/
--SELECT * FROM RawAvia WHERE ACOWN LIKE '%?%';
--PRINT SELECT COUNT(*) FROM 


-- DECLARE Experiments

/*
DECLARE @TestVariable AS VARCHAR(100)='Save Our Planet'
PRINT @TestVariable

DECLARE @PurchaseName AS NVARCHAR(50)
SELECT @PurchaseName = COUNT(*)
FROM RawAvia
WHERE FLTID = 'SK 1755'
PRINT @PurchaseName

--SELECT * FROM RawAvia; 

DECLARE @PurchaseName AS NVARCHAR(50)
SELECT @PurchaseName = CONCAT(@@ROWCOUNT, 'jhghg')
FROM RawAvia
PRINT @PurchaseName

SELECT(CONCAT(CAST(SELECT @@ROWCOUNT AS varchar), ' - bla bla bla'));
*/


-- UNION and EXISTS experiments

/*
SELECT STATION FROM STATIONS GROUP BY STATION
UNION ALL
SELECT DEPSTN FROM RawAvia GROUP BY DEPSTN

SELECT DEPSTN FROM RawAvia WHERE NOT EXISTS (SELECT STATION FROM STATIONS WHERE RawAvia.DEPSTN=STATIONS.STATION GROUP BY STATION) GROUP BY DEPSTN
UNION
SELECT ARRSTN FROM RawAvia WHERE NOT EXISTS (SELECT STATION FROM STATIONS WHERE RawAvia.ARRSTN=STATIONS.STATION GROUP BY STATION) GROUP BY ARRSTN;
*/


--BIG SELECT

/*

VAR 1

	SELECT FLTID, DATOP, ST.STATION AS DEPSTN, ST2.STATION AS ARRSTN 
	FROM LEG AS L
		LEFT JOIN LEG_CLASS AS LC
			ON L.ID=LC.ID
		LEFT JOIN STC AS S
			ON L.STC_ID=S.ID
		LEFT JOIN STATIONS AS ST
			ON L.DEPSTN=ST.ID
		LEFT JOIN STATIONS AS ST2
			ON L.ARRSTN=ST.ID
	ORDER BY DATOP, FLTID;

VAR 2

	SELECT 
		FLTID, 
		DATOP, 
		ST.STATION AS DEPSTN, 
		(SELECT STATION FROM STATIONS WHERE STATIONS.ID = L.ARRSTN) AS ARRSTN, 
		C.COUNTRY AS CTRYCDFR, 
		(SELECT COUNTRY FROM COUNTRIES WHERE COUNTRIES.ID = L.CTRYCDTO) AS CTRYCDTO,
		BLHR,
		ABHR,
		GRPNO,
		S.STC,
		A.ACREG,
		A.ACVER,
		A.ACOWN,
		A.ACTYP,
		A.ACTYP_NAME,
		LC.CLASS,
		LC.CONFIGA,
		LC.SEATED
	FROM LEG AS L
		LEFT JOIN LEG_CLASS AS LC
			ON L.ID=LC.LEG_ID
		LEFT JOIN STC AS S
			ON L.STC_ID=S.ID
		LEFT JOIN STATIONS AS ST
			ON L.DEPSTN=ST.ID
		LEFT JOIN COUNTRIES AS C
			ON L.CTRYCDFR=C.ID
		LEFT JOIN AIRCRAFT AS A
			ON L.AIRCRAFT_ID=A.ID
	ORDER BY DATOP DESC, FLTID DESC;
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'were selected from whole database';

*/

-- EXTRA optional queries


--SELECT * FROM RawAvia ORDER BY DATOP, FLTID;
--SELECT TOP 1 CONFIGA-SEATED AS Diff FROM LEG_CLASS;

--SELECT CTRYCDFR FROM RawAvia GROUP BY CTRYCDFR UNION SELECT CTRYCDTO FROM RawAvia GROUP BY CTRYCDTO;

--TRUNCATE TABLE LEG;
--SELECT @@ROWCOUNT;
--SELECT SEATED FROM RawAvia GROUP BY SEATED ORDER BY SEATED COLLATE Latin1_General_CI_AI ASC;

SELECT FLTID, DATOP, SUM(PARSE(CONFIGA AS int)) - SUM(PARSE(SEATED AS int)) AS FreeSeats

FROM RawAvia 
GROUP BY DATOP, FLTID
ORDER BY FreeSeats, DATOP, FLTID;

SELECT * FROM RawAvia ORDER BY DATOP DESC, FLTID DESC;
SELECT * FROM LOGS
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'rows affected in ';
DELETE FROM COUNTRIES WHERE ID>=40
 
SELECT CONSTRAINT_NAME,
     TABLE_SCHEMA ,
     TABLE_NAME,
     CONSTRAINT_TYPE
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS

	 SELECT MAX(FLTID),MAX(DATOP), COUNT(FLTID) AS FLTID, COUNT(DATOP) AS DATOP, COUNT(DEPSTN) AS DEPSTN, COUNT(ARRSTN) AS ARRSTN FROM RawAvia GROUP BY FLTID, DATOP,DEPSTN, ARRSTN ORDER BY FLTID;

	 SELECT * FROM RawAvia WHERE FLTID = 'SK 1755' ORDER BY DATOP DESC, FLTID DESC;