USE Stat; 
GO 

--TRUNCATE TABLE dbo.RawAvia;


/*
SELECT * FROM RawAvia where NEW_KEY = '5115402'; 
SELECT * FROM RawAvia where NEW_KEY = '5135140'; 
SELECT * FROM RawAvia where NEW_KEY = '5129911'; 
SELECT * FROM RawAvia where NEW_KEY = '5113398'; 
SELECT * FROM RawAvia where FLTID = 'SZS9160P' OR FLTID = 'SZS9160'; 
SELECT * FROM RawAvia ORDER BY NEW_KEY; 
SELECT NEW_KEY, COUNT(NEW_KEY) AS A FROM RawAvia GROUP BY NEW_KEY ORDER BY A;
SELECT NEW_KEY FROM RawAvia GROUP BY NEW_KEY ORDER BY 1;
SELECT FLTID FROM LEG GROUP BY FLTID ORDER BY 1;
*/

/*
SELECT FLTID FROM RawAvia GROUP BY FLTID ORDER BY 1;
SELECT DATOP FROM RawAvia GROUP BY DATOP ORDER BY 1;
SELECT LEGNO FROM RawAvia GROUP BY LEGNO ORDER BY 1;
SELECT DEPSTN FROM RawAvia GROUP BY DEPSTN ORDER BY 1;
SELECT ARRSTN FROM RawAvia GROUP BY ARRSTN ORDER BY 1;
SELECT CTRYCDFR FROM RawAvia GROUP BY CTRYCDFR ORDER BY 1;
SELECT CTRYCDFR FROM RawAvia GROUP BY CTRYCDFR ORDER BY 1;
SELECT BLHR FROM RawAvia GROUP BY BLHR ORDER BY 1;
SELECT ABHR FROM RawAvia GROUP BY ABHR ORDER BY 1;
SELECT GRPNO FROM RawAvia GROUP BY GRPNO ORDER BY 1;
SELECT STC FROM RawAvia GROUP BY STC ORDER BY 1;
SELECT ACREG FROM RawAvia GROUP BY ACREG ORDER BY 1;
SELECT ACVER FROM RawAvia GROUP BY ACVER ORDER BY 1;
SELECT ACOWN FROM RawAvia GROUP BY ACOWN ORDER BY 1;
SELECT ACTYP FROM RawAvia GROUP BY ACTYP ORDER BY 1;
SELECT ACTYP_NAME FROM RawAvia GROUP BY ACTYP_NAME ORDER BY 1;
SELECT CLASS FROM RawAvia GROUP BY CLASS ORDER BY 1;
SELECT CONFIGA FROM RawAvia GROUP BY CONFIGA ORDER BY 1;
SELECT SEATED FROM RawAvia GROUP BY SEATED ORDER BY 1;
SELECT PAXCAT FROM RawAvia GROUP BY PAXCAT ORDER BY 1;
SELECT BD FROM RawAvia GROUP BY BD ORDER BY 1;
SELECT TRF FROM RawAvia GROUP BY TRF ORDER BY 1;
SELECT TRT FROM RawAvia GROUP BY TRT ORDER BY 1;
*/


--SELECT * FROM RawAvia ORDER BY 3,2;
--SELECT * FROM LEG ORDER BY NEW_KEY;
--SELECT * FROM LEG_PAXCAT;

--TRUNCATE TABLE LEG;
--SELECT @@ROWCOUNT;
--SELECT SEATED FROM RawAvia GROUP BY SEATED ORDER BY SEATED COLLATE Latin1_General_CI_AI ASC;

SELECT FLTID, DATOP, SUM(PARSE(CONFIGA AS int)) - SUM(PARSE(SEATED AS int)) AS FreeSeats

FROM RawAvia 
GROUP BY DATOP, FLTID
ORDER BY FreeSeats, DATOP, FLTID;

SELECT * FROM RawAvia ORDER BY DATOP, FLTID;
SELECT * FROM LOGS
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'rows affected in ';
DELETE FROM COUNTRIES WHERE ID>=40
 