USE Stat;
GO


--table for logging(ETL and another processes)

CREATE TABLE LOGS
(
	ID int IDENTITY(1,1),
	LOG_DATA varchar(100),
	CONSTRAINT PK_LOGS_TABLE PRIMARY KEY CLUSTERED(ID) WITH (IGNORE_DUP_KEY = OFF)
);
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' - '+'LOGS table was created';


--Tables creation

CREATE TABLE STATIONS
(
	ID int IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	STATION varchar(30) NOT NULL
);
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) +' - '+'STATIONS table was created';
GO

CREATE TABLE COUNTRIES
(
	ID int IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	COUNTRY varchar(30) NOT NULL
);
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) +' - '+'COUNTRIES table was created';
GO

CREATE TABLE STC
(
	ID int IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	STC varchar(30) NOT NULL
);
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) +' - '+'STC table was created';
GO

CREATE TABLE AIRCRAFT
	(
	ID int IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	ACREG varchar(10) NOT NULL,
	ACVER varchar(10) NOT NULL,
	ACOWN varchar(3) NOT NULL,
	ACTYP varchar(3) NOT NULL,
	ACTYP_NAME varchar(50) NOT NULL
);
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) +' - '+'AIRCRAFT table was created';

CREATE TABLE LEG
(
	ID int IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	FLTID varchar(10) NOT NULL,
	DATOP date NOT NULL,
	LEGNO int NULL,
	DEPSTN int NOT NULL REFERENCES STATIONS(ID),
	ARRSTN int NOT NULL REFERENCES STATIONS(ID),
	CTRYCDFR int NOT NULL REFERENCES COUNTRIES(ID) index IX_LEG_COUNTRYFROM nonclustered,
	CTRYCDTO int NOT NULL REFERENCES COUNTRIES(ID) index IX_LEG_COUNTRYTO nonclustered,
	BLHR float NOT NULL,
	ABHR float NOT NULL,
	GRPNO varchar(10) NOT NULL,
	STC_ID int NOT NULL REFERENCES STC(ID) index IX_LEG_STC nonclustered,
	AIRCRAFT_ID int NOT NULL REFERENCES AIRCRAFT(ID) index IX_LEG_AIRCRAFT nonclustered,
	INDEX IX_LEG_NoCl NONCLUSTERED (FLTID, DATOP, DEPSTN, ARRSTN)
);
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) +' - '+'LEG table was created';
GO

CREATE TABLE LEG_CLASS
(
	ID int IDENTITY(1,1) PRIMARY KEY CLUSTERED,
	CLASS varchar(1) NOT NULL,
	CONFIGA int NOT NULL,
	SEATED int NOT NULL,
	LEG_ID int NOT NULL REFERENCES LEG(ID) index IX_LEG_CLASS_LEGID nonclustered
);
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) +' - '+'LEG_CLASS table was created';
GO


