USE Stat; 
GO 

--STC table filling

	INSERT INTO STC(STC)
		SELECT STC FROM RawAvia WHERE NOT EXISTS 
			(SELECT STC FROM STC WHERE RawAvia.STC=STC.STC GROUP BY STC) GROUP BY STC;
	INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'rows affected in STC';
	


--COUNTRIES table filling

	INSERT INTO COUNTRIES(COUNTRY)
		SELECT CTRYCDFR FROM RawAvia WHERE NOT EXISTS 
			(SELECT COUNTRY FROM COUNTRIES WHERE RawAvia.CTRYCDFR=COUNTRIES.COUNTRY GROUP BY COUNTRY) GROUP BY CTRYCDFR
	UNION
		SELECT CTRYCDTO FROM RawAvia WHERE NOT EXISTS 
			(SELECT COUNTRY FROM COUNTRIES WHERE RawAvia.CTRYCDTO=COUNTRIES.COUNTRY GROUP BY COUNTRY) GROUP BY CTRYCDTO;
	INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'rows affected in COUNTRIES';



--STATIONS table filling

	INSERT INTO STATIONS(STATION)
		SELECT DEPSTN FROM RawAvia WHERE NOT EXISTS 
			(SELECT STATION FROM STATIONS WHERE RawAvia.DEPSTN=STATIONS.STATION GROUP BY STATION) GROUP BY DEPSTN
	UNION
		SELECT ARRSTN FROM RawAvia WHERE NOT EXISTS 
			(SELECT STATION FROM STATIONS WHERE RawAvia.ARRSTN=STATIONS.STATION GROUP BY STATION) GROUP BY ARRSTN;
	INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'rows affected in STATIONS';

--AIRCRAFT table filling

	INSERT INTO AIRCRAFT(ACREG, ACVER, ACOWN, ACTYP, ACTYP_NAME)
		SELECT ACREG, ACVER, ACOWN, ACTYP, ACTYP_NAME FROM RawAvia WHERE NOT EXISTS 
				(SELECT ACREG, ACVER, ACOWN, ACTYP, ACTYP_NAME 
				FROM AIRCRAFT 
				WHERE 
					RawAvia.ACREG=AIRCRAFT.ACREG AND
					RawAvia.ACVER=AIRCRAFT.ACVER AND
					RawAvia.ACOWN=AIRCRAFT.ACOWN AND
					RawAvia.ACTYP=AIRCRAFT.ACTYP AND
					RawAvia.ACTYP_NAME=AIRCRAFT.ACTYP_NAME
				GROUP BY ACREG, ACVER, ACOWN, ACTYP, ACTYP_NAME) 
			GROUP BY ACREG, ACVER, ACOWN, ACTYP, ACTYP_NAME;
	INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'rows affected in AIRCRAFT';

--LEG table filling

INSERT INTO LEG(FLTID, DATOP, LEGNO, DEPSTN, ARRSTN, CTRYCDFR, CTRYCDTO, BLHR, ABHR, GRPNO, STC_ID, AIRCRAFT_ID) 
	SELECT 
		FLTID, 
		DATOP, 
		LEGNO, 
		(SELECT TOP 1 ID FROM STATIONS WHERE STATION = RawAvia.DEPSTN) AS DEPSTN, 
		(SELECT TOP 1 ID FROM STATIONS WHERE STATION = RawAvia.ARRSTN) AS ARRSTN, 
		(SELECT TOP 1 ID FROM COUNTRIES WHERE COUNTRY = RawAvia.CTRYCDFR) AS CTRYCDFR,
		(SELECT TOP 1 ID FROM COUNTRIES WHERE COUNTRY = RawAvia.CTRYCDTO) AS CTRYCDTO,
		BLHR,
		ABHR,
		GRPNO,
		(SELECT TOP 1 ID FROM STC WHERE STC = RawAvia.STC) AS STC,
		(SELECT TOP 1 ID FROM AIRCRAFT WHERE ACREG = RawAvia.ACREG AND ACVER = RawAvia.ACVER) AS AIRCRAFT
	FROM RawAvia

GROUP BY FLTID, DATOP, LEGNO,DEPSTN, ARRSTN, CTRYCDFR, CTRYCDTO, BLHR, ABHR, GRPNO, STC, ACREG, ACVER
ORDER BY DATOP, FLTID, DEPSTN, ARRSTN;
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'rows affected in LEG';


--LEG_CLASS table filling

INSERT INTO LEG_CLASS(CLASS, CONFIGA, SEATED, LEG_ID) 
	SELECT
	CLASS, 
	CONFIGA, 
	PARSE(SEATED AS int), 

		(SELECT TOP 1 ID 
		FROM LEG 
		WHERE 
		FLTID = RawAvia.FLTID 
		AND 
		DATOP = CAST(RawAvia.DATOP AS date) 
		AND 
			(SELECT TOP 1 STATION FROM STATIONS WHERE ID = DEPSTN) = RawAvia.DEPSTN 
		AND 
			(SELECT TOP 1 STATION FROM STATIONS WHERE ID = ARRSTN) = RawAvia.ARRSTN) AS FLTDI 

FROM RawAvia 
GROUP BY CLASS, CONFIGA, SEATED, FLTID, DATOP, DEPSTN, ARRSTN
ORDER BY DATOP, FLTID;
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'rows affected in LEG_CLASS';


--SELECTing from whole base
	
	SELECT 
		FLTID, 
		DATOP, 
		ST.STATION AS DEPSTN, 
		(SELECT STATION FROM STATIONS WHERE STATIONS.ID = L.ARRSTN) AS ARRSTN, 
		C.COUNTRY AS CTRYCDFR, 
		(SELECT COUNTRY FROM COUNTRIES WHERE COUNTRIES.ID = L.CTRYCDTO) AS CTRYCDTO,
		BLHR,
		ABHR,
		GRPNO,
		S.STC,
		A.ACREG,
		A.ACVER,
		A.ACOWN,
		A.ACTYP,
		A.ACTYP_NAME,
		LC.CLASS,
		LC.CONFIGA,
		LC.SEATED
	FROM LEG AS L
		LEFT JOIN LEG_CLASS AS LC
			ON L.ID=LC.LEG_ID
		LEFT JOIN STC AS S
			ON L.STC_ID=S.ID
		LEFT JOIN STATIONS AS ST
			ON L.DEPSTN=ST.ID
		LEFT JOIN COUNTRIES AS C
			ON L.CTRYCDFR=C.ID
		LEFT JOIN AIRCRAFT AS A
			ON L.AIRCRAFT_ID=A.ID
	ORDER BY DATOP DESC, FLTID DESC;
INSERT INTO LOGS(LOG_DATA) SELECT CAST(GETDATE() AS varchar(20)) + ' -  '+ CAST(@@ROWCOUNT AS varchar(10))+' - '+'were selected from whole database';